In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import os

In [8]:
F1=pd.read_csv('2019great-britainF1.csv') #reading csv files

In [9]:
F1 #need to add header

,1,44,Lewis,Hamilton,HAM,Mercedes,52,1:21:08.452,26
0,2,77,Valtteri,Bottas,BOT,Mercedes,52,+24.928s,18
1,3,16,Charles,Leclerc,LEC,Ferrari,52,+30.117s,15
2,4,10,Pierre,Gasly,GAS,Red Bull Racing Honda,52,+34.692s,12
3,5,33,Max,Verstappen,VER,Red Bull Racing Honda,52,+39.458s,10
4,6,55,Carlos,Sainz,SAI,McLaren Renault,52,+53.639s,8
5,7,3,Daniel,Ricciardo,RIC,Renault,52,+54.401s,6
6,8,7,Kimi,RÃ¤ikkÃ¶nen,RAI,Alfa Romeo Racing Ferrari,52,+65.540s,4
7,9,26,Daniil,Kvyat,KVY,Scuderia Toro Rosso Honda,52,+66.720s,2
8,10,27,Nico,Hulkenberg,HUL,Renault,52,+72.733s,1
9,11,4,Lando,Norris,NOR,McLaren Renault,52,+74.281s,0
10,12,23,Alexander,Albon,ALB,Scuderia Toro Rosso Honda,52,+75.617s,0
11,13,18,Lance,Stroll,STR,Racing Point BWT Mercedes,52,+81.086s,0
12,14,63,George,Russell,RUS,Williams Mercedes,51,+1 lap,0
13,15,88,Robert,Kubica,KUB,Williams Mercedes,51,+1 lap,0
14,16,5,Sebastian,Vettel,VET,Ferrari,51,+1 lap,0
15,17,11,Sergio,Perez,PER,Racing Point BWT Mercedes,51,+1 lap,0
16,NC,99,Antonio,Giovinazzi,GIO,Alfa Romeo Racing Ferrari,18,DNF,0
17,NC,8,Romain,Grosjean,GRO,Haas Ferrari,9,DNF,0
18,NC,20,Kevin,Magnussen,MAG,Haas Ferrari,6,DNF,0

In [29]:
F1header = pd.Series(['POS', 'NO', 'DriverFName','DriverLName', 'NameAbrv', 'Car', 'Laps', 'Time/DNF', 'PTS'])

In [16]:
F1header

0            POS
1             NO
2    DriverFName
3    DriverLName
4    NameAbrvCar
5           Laps
6       Time/DNF
7            PTS
dtype: object

In [17]:
F1=pd.read_csv('2019great-britainF1.csv', names = F1header)

In [18]:
F1 #index issue

,POS,NO,DriverFName,DriverLName,NameAbrvCar,Laps,Time/DNF,PTS
1,44,Lewis,Hamilton,HAM,Mercedes,52,1:21:08.452,26
2,77,Valtteri,Bottas,BOT,Mercedes,52,+24.928s,18
3,16,Charles,Leclerc,LEC,Ferrari,52,+30.117s,15
4,10,Pierre,Gasly,GAS,Red Bull Racing Honda,52,+34.692s,12
5,33,Max,Verstappen,VER,Red Bull Racing Honda,52,+39.458s,10
6,55,Carlos,Sainz,SAI,McLaren Renault,52,+53.639s,8
7,3,Daniel,Ricciardo,RIC,Renault,52,+54.401s,6
8,7,Kimi,RÃ¤ikkÃ¶nen,RAI,Alfa Romeo Racing Ferrari,52,+65.540s,4
9,26,Daniil,Kvyat,KVY,Scuderia Toro Rosso Honda,52,+66.720s,2
10,27,Nico,Hulkenberg,HUL,Renault,52,+72.733s,1
11,4,Lando,Norris,NOR,McLaren Renault,52,+74.281s,0
12,23,Alexander,Albon,ALB,Scuderia Toro Rosso Honda,52,+75.617s,0
13,18,Lance,Stroll,STR,Racing Point BWT Mercedes,52,+81.086s,0
14,63,George,Russell,RUS,Williams Mercedes,51,+1 lap,0
15,88,Robert,Kubica,KUB,Williams Mercedes,51,+1 lap,0
16,5,Sebastian,Vettel,VET,Ferrari,51,+1 lap,0
17,11,Sergio,Perez,PER,Racing Point BWT Mercedes,51,+1 lap,0
NC,99,Antonio,Giovinazzi,GIO,Alfa Romeo Racing Ferrari,18,DNF,0
NC,8,Romain,Grosjean,GRO,Haas Ferrari,9,DNF,0
NC,20,Kevin,Magnussen,MAG,Haas Ferrari,6,DNF,0

In [19]:
F1.index.name = 'id'

In [20]:
F1

,POS,NO,DriverFName,DriverLName,NameAbrvCar,Laps,Time/DNF,PTS
id,,,,,,,,
1,44,Lewis,Hamilton,HAM,Mercedes,52,1:21:08.452,26
2,77,Valtteri,Bottas,BOT,Mercedes,52,+24.928s,18
3,16,Charles,Leclerc,LEC,Ferrari,52,+30.117s,15
4,10,Pierre,Gasly,GAS,Red Bull Racing Honda,52,+34.692s,12
5,33,Max,Verstappen,VER,Red Bull Racing Honda,52,+39.458s,10
6,55,Carlos,Sainz,SAI,McLaren Renault,52,+53.639s,8
7,3,Daniel,Ricciardo,RIC,Renault,52,+54.401s,6
8,7,Kimi,RÃ¤ikkÃ¶nen,RAI,Alfa Romeo Racing Ferrari,52,+65.540s,4
9,26,Daniil,Kvyat,KVY,Scuderia Toro Rosso Honda,52,+66.720s,2
10,27,Nico,Hulkenberg,HUL,Renault,52,+72.733s,1
11,4,Lando,Norris,NOR,McLaren Renault,52,+74.281s,0
12,23,Alexander,Albon,ALB,Scuderia Toro Rosso Honda,52,+75.617s,0
13,18,Lance,Stroll,STR,Racing Point BWT Mercedes,52,+81.086s,0
14,63,George,Russell,RUS,Williams Mercedes,51,+1 lap,0
15,88,Robert,Kubica,KUB,Williams Mercedes,51,+1 lap,0
16,5,Sebastian,Vettel,VET,Ferrari,51,+1 lap,0
17,11,Sergio,Perez,PER,Racing Point BWT Mercedes,51,+1 lap,0
NC,99,Antonio,Giovinazzi,GIO,Alfa Romeo Racing Ferrari,18,DNF,0
NC,8,Romain,Grosjean,GRO,Haas Ferrari,9,DNF,0
NC,20,Kevin,Magnussen,MAG,Haas Ferrari,6,DNF,0

In [23]:
F1.index = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19] #wrong

In [24]:
F1 #very wrong

,POS,NO,DriverFName,DriverLName,NameAbrvCar,Laps,Time/DNF,PTS
0,44,Lewis,Hamilton,HAM,Mercedes,52,1:21:08.452,26
1,77,Valtteri,Bottas,BOT,Mercedes,52,+24.928s,18
2,16,Charles,Leclerc,LEC,Ferrari,52,+30.117s,15
3,10,Pierre,Gasly,GAS,Red Bull Racing Honda,52,+34.692s,12
4,33,Max,Verstappen,VER,Red Bull Racing Honda,52,+39.458s,10
5,55,Carlos,Sainz,SAI,McLaren Renault,52,+53.639s,8
6,3,Daniel,Ricciardo,RIC,Renault,52,+54.401s,6
7,7,Kimi,RÃ¤ikkÃ¶nen,RAI,Alfa Romeo Racing Ferrari,52,+65.540s,4
8,26,Daniil,Kvyat,KVY,Scuderia Toro Rosso Honda,52,+66.720s,2
9,27,Nico,Hulkenberg,HUL,Renault,52,+72.733s,1
10,4,Lando,Norris,NOR,McLaren Renault,52,+74.281s,0
11,23,Alexander,Albon,ALB,Scuderia Toro Rosso Honda,52,+75.617s,0
12,18,Lance,Stroll,STR,Racing Point BWT Mercedes,52,+81.086s,0
13,63,George,Russell,RUS,Williams Mercedes,51,+1 lap,0
14,88,Robert,Kubica,KUB,Williams Mercedes,51,+1 lap,0
15,5,Sebastian,Vettel,VET,Ferrari,51,+1 lap,0
16,11,Sergio,Perez,PER,Racing Point BWT Mercedes,51,+1 lap,0
17,99,Antonio,Giovinazzi,GIO,Alfa Romeo Racing Ferrari,18,DNF,0
18,8,Romain,Grosjean,GRO,Haas Ferrari,9,DNF,0
19,20,Kevin,Magnussen,MAG,Haas Ferrari,6,DNF,0

In [30]:
F1=pd.read_csv('2019great-britainF1.csv', names = F1header, index_col = False) #works

In [31]:
F1

,POS,NO,DriverFName,DriverLName,NameAbrv,Car,Laps,Time/DNF,PTS
0,1,44,Lewis,Hamilton,HAM,Mercedes,52,1:21:08.452,26
1,2,77,Valtteri,Bottas,BOT,Mercedes,52,+24.928s,18
2,3,16,Charles,Leclerc,LEC,Ferrari,52,+30.117s,15
3,4,10,Pierre,Gasly,GAS,Red Bull Racing Honda,52,+34.692s,12
4,5,33,Max,Verstappen,VER,Red Bull Racing Honda,52,+39.458s,10
5,6,55,Carlos,Sainz,SAI,McLaren Renault,52,+53.639s,8
6,7,3,Daniel,Ricciardo,RIC,Renault,52,+54.401s,6
7,8,7,Kimi,RÃ¤ikkÃ¶nen,RAI,Alfa Romeo Racing Ferrari,52,+65.540s,4
8,9,26,Daniil,Kvyat,KVY,Scuderia Toro Rosso Honda,52,+66.720s,2
9,10,27,Nico,Hulkenberg,HUL,Renault,52,+72.733s,1
10,11,4,Lando,Norris,NOR,McLaren Renault,52,+74.281s,0
11,12,23,Alexander,Albon,ALB,Scuderia Toro Rosso Honda,52,+75.617s,0
12,13,18,Lance,Stroll,STR,Racing Point BWT Mercedes,52,+81.086s,0
13,14,63,George,Russell,RUS,Williams Mercedes,51,+1 lap,0
14,15,88,Robert,Kubica,KUB,Williams Mercedes,51,+1 lap,0
15,16,5,Sebastian,Vettel,VET,Ferrari,51,+1 lap,0
16,17,11,Sergio,Perez,PER,Racing Point BWT Mercedes,51,+1 lap,0
17,NC,99,Antonio,Giovinazzi,GIO,Alfa Romeo Racing Ferrari,18,DNF,0
18,NC,8,Romain,Grosjean,GRO,Haas Ferrari,9,DNF,0
19,NC,20,Kevin,Magnussen,MAG,Haas Ferrari,6,DNF,0

In [32]:
F1.iloc[1]

POS                   2
NO                   77
DriverFName    Valtteri
DriverLName      Bottas
NameAbrv            BOT
Car            Mercedes
Laps                 52
Time/DNF       +24.928s
PTS                  18
Name: 1, dtype: object

In [33]:
F1.index.name = 'ID'

In [34]:
F1

,POS,NO,DriverFName,DriverLName,NameAbrv,Car,Laps,Time/DNF,PTS
ID,,,,,,,,,
0,1,44,Lewis,Hamilton,HAM,Mercedes,52,1:21:08.452,26
1,2,77,Valtteri,Bottas,BOT,Mercedes,52,+24.928s,18
2,3,16,Charles,Leclerc,LEC,Ferrari,52,+30.117s,15
3,4,10,Pierre,Gasly,GAS,Red Bull Racing Honda,52,+34.692s,12
4,5,33,Max,Verstappen,VER,Red Bull Racing Honda,52,+39.458s,10
5,6,55,Carlos,Sainz,SAI,McLaren Renault,52,+53.639s,8
6,7,3,Daniel,Ricciardo,RIC,Renault,52,+54.401s,6
7,8,7,Kimi,RÃ¤ikkÃ¶nen,RAI,Alfa Romeo Racing Ferrari,52,+65.540s,4
8,9,26,Daniil,Kvyat,KVY,Scuderia Toro Rosso Honda,52,+66.720s,2
9,10,27,Nico,Hulkenberg,HUL,Renault,52,+72.733s,1
10,11,4,Lando,Norris,NOR,McLaren Renault,52,+74.281s,0
11,12,23,Alexander,Albon,ALB,Scuderia Toro Rosso Honda,52,+75.617s,0
12,13,18,Lance,Stroll,STR,Racing Point BWT Mercedes,52,+81.086s,0
13,14,63,George,Russell,RUS,Williams Mercedes,51,+1 lap,0
14,15,88,Robert,Kubica,KUB,Williams Mercedes,51,+1 lap,0
15,16,5,Sebastian,Vettel,VET,Ferrari,51,+1 lap,0
16,17,11,Sergio,Perez,PER,Racing Point BWT Mercedes,51,+1 lap,0
17,NC,99,Antonio,Giovinazzi,GIO,Alfa Romeo Racing Ferrari,18,DNF,0
18,NC,8,Romain,Grosjean,GRO,Haas Ferrari,9,DNF,0
19,NC,20,Kevin,Magnussen,MAG,Haas Ferrari,6,DNF,0

In [35]:
F1.index.name = ''

In [36]:
F1

,POS,NO,DriverFName,DriverLName,NameAbrv,Car,Laps,Time/DNF,PTS
,,,,,,,,,
0,1,44,Lewis,Hamilton,HAM,Mercedes,52,1:21:08.452,26
1,2,77,Valtteri,Bottas,BOT,Mercedes,52,+24.928s,18
2,3,16,Charles,Leclerc,LEC,Ferrari,52,+30.117s,15
3,4,10,Pierre,Gasly,GAS,Red Bull Racing Honda,52,+34.692s,12
4,5,33,Max,Verstappen,VER,Red Bull Racing Honda,52,+39.458s,10
5,6,55,Carlos,Sainz,SAI,McLaren Renault,52,+53.639s,8
6,7,3,Daniel,Ricciardo,RIC,Renault,52,+54.401s,6
7,8,7,Kimi,RÃ¤ikkÃ¶nen,RAI,Alfa Romeo Racing Ferrari,52,+65.540s,4
8,9,26,Daniil,Kvyat,KVY,Scuderia Toro Rosso Honda,52,+66.720s,2
9,10,27,Nico,Hulkenberg,HUL,Renault,52,+72.733s,1
10,11,4,Lando,Norris,NOR,McLaren Renault,52,+74.281s,0
11,12,23,Alexander,Albon,ALB,Scuderia Toro Rosso Honda,52,+75.617s,0
12,13,18,Lance,Stroll,STR,Racing Point BWT Mercedes,52,+81.086s,0
13,14,63,George,Russell,RUS,Williams Mercedes,51,+1 lap,0
14,15,88,Robert,Kubica,KUB,Williams Mercedes,51,+1 lap,0
15,16,5,Sebastian,Vettel,VET,Ferrari,51,+1 lap,0
16,17,11,Sergio,Perez,PER,Racing Point BWT Mercedes,51,+1 lap,0
17,NC,99,Antonio,Giovinazzi,GIO,Alfa Romeo Racing Ferrari,18,DNF,0
18,NC,8,Romain,Grosjean,GRO,Haas Ferrari,9,DNF,0
19,NC,20,Kevin,Magnussen,MAG,Haas Ferrari,6,DNF,0

In [44]:
F1.dtypes

POS            object
NO              int64
DriverFName    object
DriverLName    object
NameAbrv       object
Car            object
Laps            int64
Time/DNF       object
PTS             int64
dtype: object

In [45]:
F1top3=pd.read_csv('2019great-britainF1.csv', names =F1header, index_col = False, nrows=3)

In [46]:
F1top3

   POS  NO DriverFName DriverLName NameAbrv       Car  Laps     Time/DNF  PTS
0    1  44       Lewis    Hamilton      HAM  Mercedes    52  1:21:08.452   26
1    2  77    Valtteri      Bottas      BOT  Mercedes    52     +24.928s   18
2    3  16     Charles     Leclerc      LEC   Ferrari    52     +30.117s   15

In [47]:
F1top3.to_csv('Britain19Top3.csv')

In [48]:
#working with JSON

In [4]:
import json

In [5]:
prizedata = pd.read_json('prize2010.json')

In [51]:
prizedata.head()

                                              prizes
0  {'year': '2020', 'category': 'chemistry', 'lau...
1  {'year': '2020', 'category': 'economics', 'lau...
2  {'year': '2020', 'category': 'literature', 'la...
3  {'year': '2020', 'category': 'peace', 'laureat...
4  {'year': '2020', 'category': 'physics', 'laure...

In [13]:
pd.options.display.max_rows = 8

In [16]:
data = [{'state': 'Florida',

         'shortname': 'FL',

         'info': {'governor': 'Rick Scott'},

         'counties': [{'name': 'Dade', 'population': 12345},

                      {'name': 'Broward', 'population': 40000},

                      {'name': 'Palm Beach', 'population': 60000}]},

        {'state': 'Ohio',

         'shortname': 'OH',

         'info': {'governor': 'John Kasich'},

         'counties': [{'name': 'Summit', 'population': 1234},

                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [18]:
result = pd.json_normalize(data, 'counties')

In [19]:
prized=[{'year': '2020',
   'category': 'chemistry',
   'laureates': [{'firstname': 'Emmanuelle','surname': 'Charpentier'},
                  {'firstname': 'Jennifer A.','surname': 'Doudna'}
                ]
  },
  {'year': '2020',
   'category': 'economics',
   'laureates': [{'firstname': 'Paul','surname': 'Milgrom'},
                  {'firstname': 'Robert','surname': 'Wilson'}
                ]
  }]

In [22]:
prize_result = pd.json_normalize(prized, 'laureates', meta = ['year', 'category'])

In [23]:
prize_result

     firstname      surname  year   category
0   Emmanuelle  Charpentier  2020  chemistry
1  Jennifer A.       Doudna  2020  chemistry
2         Paul      Milgrom  2020  economics
3       Robert       Wilson  2020  economics

In [25]:
with open('prize2010.json') as f:
    d = json.load(f)

In [26]:
d

{'prizes': [{'year': '2020',
   'category': 'chemistry',
   'laureates': [{'id': '991',
     'firstname': 'Emmanuelle',
     'surname': 'Charpentier',
     'motivation': '"for the development of a method for genome editing"',
     'share': '2'},
    {'id': '992',
     'firstname': 'Jennifer A.',
     'surname': 'Doudna',
     'motivation': '"for the development of a method for genome editing"',
     'share': '2'}]},
  {'year': '2020',
   'category': 'economics',
   'laureates': [{'id': '995',
     'firstname': 'Paul',
     'surname': 'Milgrom',
     'motivation': '"for improvements to auction theory and inventions of new auction formats"',
     'share': '2'},
    {'id': '996',
     'firstname': 'Robert',
     'surname': 'Wilson',
     'motivation': '"for improvements to auction theory and inventions of new auction formats"',
     'share': '2'}]},
  {'year': '2020',
   'category': 'literature',
   'laureates': [{'id': '993',
     'firstname': 'Louise',
     'surname': 'Glück',
     'motivation': '"for her unmistakable poetic voice that with austere beauty makes individual existence universal"',
     'share': '1'}]},
  {'year': '2020',
   'category': 'peace',
   'laureates': [{'id': '994',
     'motivation': '"for its efforts to combat hunger, for its contribution to bettering conditions for peace in conflict-affected areas and for acting as a driving force in efforts to prevent the use of hunger as a weapon of war and conflict"',
     'share': '1',
     'firstname': 'World Food Programme'}]},
  {'year': '2020',
   'category': 'physics',
   'laureates': [{'id': '988',
     'firstname': 'Roger',
     'surname': 'Penrose',
     'motivation': '"for the discovery that black hole formation is a robust prediction of the general theory of relativity"',
     'share': '2'},
    {'id': '989',
     'firstname': 'Reinhard',
     'surname': 'Genzel',
     'motivation': '"for the discovery of a supermassive compact object at the centre of our galaxy"',
     'share': '4'},
    {'id': '990',
     'firstname': 'Andrea',
     'surname': 'Ghez',
     'motivation': '"for the discovery of a supermassive compact object at the centre of our galaxy"',
     'share': '4'}]},
  {'year': '2020',
   'category': 'medicine',
   'laureates': [{'id': '985',
     'firstname': 'Harvey',
     'surname': 'Alter',
     'motivation': '"for the discovery of Hepatitis C virus"',
     'share': '3'},
    {'id': '986',
     'firstname': 'Michael',
     'surname': 'Houghton',
     'motivation': '"for the discovery of Hepatitis C virus"',
     'share': '3'},
    {'id': '987',
     'firstname': 'Charles',
     'surname': 'Rice',
     'motivation': '"for the discovery of Hepatitis C virus"',
     'share': '3'}]},
  {'year': '2019',
   'category': 'chemistry',
   'laureates': [{'id': '976',
     'firstname': 'John',
     'surname': 'Goodenough',
     'motivation': '"for the development of lithium-ion batteries"',
     'share': '3'},
    {'id': '977',
     'firstname': 'M. Stanley',
     'surname': 'Whittingham',
     'motivation': '"for the development of lithium-ion batteries"',
     'share': '3'},
    {'id': '978',
     'firstname': 'Akira',
     'surname': 'Yoshino',
     'motivation': '"for the development of lithium-ion batteries"',
     'share': '3'}]},
  {'year': '2019',
   'category': 'economics',
   'laureates': [{'id': '982',
     'firstname': 'Abhijit',
     'surname': 'Banerjee',
     'motivation': '"for their experimental approach to alleviating global poverty"',
     'share': '3'},
    {'id': '983',
     'firstname': 'Esther',
     'surname': 'Duflo',
     'motivation': '"for their experimental approach to alleviating global poverty"',
     'share': '3'},
    {'id': '984',
     'firstname': 'Michael',
     'surname': 'Kremer',
     'motivation': '"for their experimental approach to alleviating global poverty"',
     'share': '3'}]},
  {'year': '2019',
   'category': 'literature',
   'laureates': [{'id': '980',
     'firstname': 'Peter',
     'surname': 'Handke',
     'motivation': '"for an influential work that with linguistic ingenuity has explored the periphery and the specificity of human experience"',
     'share': '1'}]},
  {'year': '2019',
   'category': 'peace',
   'laureates': [{'id': '981',
     'firstname': 'Abiy',
     'surname': 'Ahmed Ali',
     'motivation': '"for his efforts to achieve peace and international cooperation, and in particular for his decisive initiative to resolve the border conflict with neighbouring Eritrea"',
     'share': '1'}]},
  {'year': '2019',
   'category': 'physics',
   'overallMotivation': '"for contributions to our understanding of the evolution of the universe and Earth’s place in the cosmos"',
   'laureates': [{'id': '973',
     'firstname': 'James',
     'surname': 'Peebles',
     'motivation': '"for theoretical discoveries in physical cosmology"',
     'share': '2'},
    {'id': '974',
     'firstname': 'Michel',
     'surname': 'Mayor',
     'motivation': '"for the discovery of an exoplanet orbiting a solar-type star"',
     'share': '4'},
    {'id': '975',
     'firstname': 'Didier',
     'surname': 'Queloz',
     'motivation': '"for the discovery of an exoplanet orbiting a solar-type star"',
     'share': '4'}]},
  {'year': '2019',
   'category': 'medicine',
   'laureates': [{'id': '970',
     'firstname': 'William',
     'surname': 'Kaelin',
     'motivation': '"for their discoveries of how cells sense and adapt to oxygen availability"',
     'share': '3'},
    {'id': '971',
     'firstname': 'Peter',
     'surname': 'Ratcliffe',
     'motivation': '"for their discoveries of how cells sense and adapt to oxygen availability"',
     'share': '3'},
    {'id': '972',
     'firstname': 'Gregg',
     'surname': 'Semenza',
     'motivation': '"for their discoveries of how cells sense and adapt to oxygen availability"',
     'share': '3'}]},
  {'year': '2018',
   'category': 'chemistry',
   'laureates': [{'id': '963',
     'firstname': 'Frances H.',
     'surname': 'Arnold',
     'motivation': '"for the directed evolution of enzymes"',
     'share': '2'},
    {'id': '964',
     'firstname': 'George P.',
     'surname': 'Smith',
     'motivation': '"for the phage display of peptides and antibodies"',
     'share': '4'},
    {'id': '965',
     'firstname': 'Sir Gregory P.',
     'surname': 'Winter',
     'motivation': '"for the phage display of peptides and antibodies"',
     'share': '4'}]},
  {'year': '2018',
   'category': 'economics',
   'laureates': [{'id': '968',
     'firstname': 'William D.',
     'surname': 'Nordhaus',
     'motivation': '"for integrating climate change into long-run macroeconomic analysis"',
     'share': '2'},
    {'id': '969',
     'firstname': 'Paul M.',
     'surname': 'Romer',
     'motivation': '"for integrating technological innovations into long-run macroeconomic analysis"',
     'share': '2'}]},
  {'year': '2018',
   'category': 'literature',
   'laureates': [{'id': '979',
     'firstname': 'Olga',
     'surname': 'Tokarczuk',
     'motivation': '"for a narrative imagination that with encyclopedic passion represents the crossing of boundaries as a form of life"',
     'share': '1'}]},
  {'year': '2018',
   'category': 'peace',
   'laureates': [{'id': '966',
     'firstname': 'Denis',
     'surname': 'Mukwege',
     'motivation': '"for their efforts to end the use of sexual violence as a weapon of war and armed conflict"',
     'share': '2'},
    {'id': '967',
     'firstname': 'Nadia',
     'surname': 'Murad',
     'motivation': '"for their efforts to end the use of sexual violence as a weapon of war and armed conflict"',
     'share': '2'}]},
  {'year': '2018',
   'category': 'physics',
   'overallMotivation': '"for groundbreaking inventions in the field of laser physics"',
   'laureates': [{'id': '960',
     'firstname': 'Arthur',
     'surname': 'Ashkin',
     'motivation': '"for the optical tweezers and their application to biological systems"',
     'share': '2'},
    {'id': '961',
     'firstname': 'Gérard',
     'surname': 'Mourou',
     'motivation': '"for their method of generating high-intensity, ultra-short optical pulses"',
     'share': '4'},
    {'id': '962',
     'firstname': 'Donna',
     'surname': 'Strickland',
     'motivation': '"for their method of generating high-intensity, ultra-short optical pulses"',
     'share': '4'}]},
  {'year': '2018',
   'category': 'medicine',
   'laureates': [{'id': '958',
     'firstname': 'James P.',
     'surname': 'Allison',
     'motivation': '"for their discovery of cancer therapy by inhibition of negative immune regulation"',
     'share': '2'},
    {'id': '959',
     'firstname': 'Tasuku',
     'surname': 'Honjo',
     'motivation': '"for their discovery of cancer therapy by inhibition of negative immune regulation"',
     'share': '2'}]},
  {'year': '2017',
   'category': 'chemistry',
   'laureates': [{'id': '944',
     'firstname': 'Jacques',
     'surname': 'Dubochet',
     'motivation': '"for developing cryo-electron microscopy for the high-resolution structure determination of biomolecules in solution"',
     'share': '3'},
    {'id': '945',
     'firstname': 'Joachim',
     'surname': 'Frank',
     'motivation': '"for developing cryo-electron microscopy for the high-resolution structure determination of biomolecules in solution"',
     'share': '3'},
    {'id': '946',
     'firstname': 'Richard',
     'surname': 'Henderson',
     'motivation': '"for developing cryo-electron microscopy for the high-resolution structure determination of biomolecules in solution"',
     'share': '3'}]},
  {'year': '2017',
   'category': 'economics',
   'laureates': [{'id': '949',
     'firstname': 'Richard H.',
     'surname': 'Thaler',
     'motivation': '"for his contributions to behavioural economics"',
     'share': '1'}]},
  {'year': '2017',
   'category': 'literature',
   'laureates': [{'id': '947',
     'firstname': 'Kazuo',
     'surname': 'Ishiguro',
     'motivation': '"who, in novels of great emotional force, has uncovered the abyss beneath our illusory sense of connection with the world"',
     'share': '1'}]},
  {'year': '2017',
   'category': 'peace',
   'laureates': [{'id': '948',
     'motivation': '"for its work to draw attention to the catastrophic humanitarian consequences of any use of nuclear weapons and for its ground-breaking efforts to achieve a treaty-based prohibition of such weapons"',
     'share': '1',
     'firstname': 'International Campaign to Abolish Nuclear Weapons (ICAN)'}]},
  {'year': '2017',
   'category': 'physics',
   'laureates': [{'id': '941',
     'firstname': 'Rainer',
     'surname': 'Weiss',
     'motivation': '"for decisive contributions to the LIGO detector and the observation of gravitational waves"',
     'share': '2'},
    {'id': '942',
     'firstname': 'Barry C.',
     'surname': 'Barish',
     'motivation': '"for decisive contributions to the LIGO detector and the observation of gravitational waves"',
     'share': '4'},
    {'id': '943',
     'firstname': 'Kip S.',
     'surname': 'Thorne',
     'motivation': '"for decisive contributions to the LIGO detector and the observation of gravitational waves"',
     'share': '4'}]},
  {'year': '2017',
   'category': 'medicine',
   'laureates': [{'id': '938',
     'firstname': 'Jeffrey C.',
     'surname': 'Hall',
     'motivation': '"for their discoveries of molecular mechanisms controlling the circadian rhythm"',
     'share': '3'},
    {'id': '939',
     'firstname': 'Michael',
     'surname': 'Rosbash',
     'motivation': '"for their discoveries of molecular mechanisms controlling the circadian rhythm"',
     'share': '3'},
    {'id': '940',
     'firstname': 'Michael W.',
     'surname': 'Young',
     'motivation': '"for their discoveries of molecular mechanisms controlling the circadian rhythm"',
     'share': '3'}]},
  {'year': '2016',
   'category': 'chemistry',
   'laureates': [{'id': '931',
     'firstname': 'Jean-Pierre',
     'surname': 'Sauvage',
     'motivation': '"for the design and synthesis of molecular machines"',
     'share': '3'},
    {'id': '932',
     'firstname': 'Sir J. Fraser',
     'surname': 'Stoddart',
     'motivation': '"for the design and synthesis of molecular machines"',
     'share': '3'},
    {'id': '933',
     'firstname': 'Bernard L.',
     'surname': 'Feringa',
     'motivation': '"for the design and synthesis of molecular machines"',
     'share': '3'}]},
  {'year': '2016',
   'category': 'economics',
   'laureates': [{'id': '935',
     'firstname': 'Oliver',
     'surname': 'Hart',
     'motivation': '"for their contributions to contract theory"',
     'share': '2'},
    {'id': '936',
     'firstname': 'Bengt',
     'surname': 'Holmström',
     'motivation': '"for their contributions to contract theory"',
     'share': '2'}]},
  {'year': '2016',
   'category': 'literature',
   'laureates': [{'id': '937',
     'firstname': 'Bob',
     'surname': 'Dylan',
     'motivation': '"for having created new poetic expressions within the great American song tradition"',
     'share': '1'}]},
  {'year': '2016',
   'category': 'peace',
   'laureates': [{'id': '934',
     'firstname': 'Juan Manuel',
     'surname': 'Santos',
     'motivation': '"for his resolute efforts to bring the country\x92\'s more than 50-year-long civil war to an end"',
     'share': '1'}]},
  {'year': '2016',
   'category': 'physics',
   'laureates': [{'id': '928',
     'firstname': 'David J.',
     'surname': 'Thouless',
     'motivation': '"for theoretical discoveries of topological phase transitions and topological phases of matter"',
     'share': '2'},
    {'id': '929',
     'firstname': 'F. Duncan M.',
     'surname': 'Haldane',
     'motivation': '"for theoretical discoveries of topological phase transitions and topological phases of matter"',
     'share': '4'},
    {'id': '930',
     'firstname': 'J. Michael',
     'surname': 'Kosterlitz',
     'motivation': '"for theoretical discoveries of topological phase transitions and topological phases of matter"',
     'share': '4'}]},
  {'year': '2016',
   'category': 'medicine',
   'laureates': [{'id': '927',
     'firstname': 'Yoshinori',
     'surname': 'Ohsumi',
     'motivation': '"for his discoveries of mechanisms for autophagy"',
     'share': '1'}]},
  {'year': '2015',
   'category': 'chemistry',
   'laureates': [{'id': '921',
     'firstname': 'Tomas',
     'surname': 'Lindahl',
     'motivation': '"for mechanistic studies of DNA repair"',
     'share': '3'},
    {'id': '922',
     'firstname': 'Paul',
     'surname': 'Modrich',
     'motivation': '"for mechanistic studies of DNA repair"',
     'share': '3'},
    {'id': '923',
     'firstname': 'Aziz',
     'surname': 'Sancar',
     'motivation': '"for mechanistic studies of DNA repair"',
     'share': '3'}]},
  {'year': '2015',
   'category': 'economics',
   'laureates': [{'id': '926',
     'firstname': 'Angus',
     'surname': 'Deaton',
     'motivation': '"for his analysis of consumption, poverty, and welfare"',
     'share': '1'}]},
  {'year': '2015',
   'category': 'literature',
   'laureates': [{'id': '924',
     'firstname': 'Svetlana',
     'surname': 'Alexievich',
     'motivation': '"for her polyphonic writings, a monument to suffering and courage in our time"',
     'share': '1'}]},
  {'year': '2015',
   'category': 'peace',
   'laureates': [{'id': '925',
     'motivation': '"for its decisive contribution to the building of a pluralistic democracy in Tunisia in the wake of the Jasmine Revolution of 2011"',
     'share': '1',
     'firstname': 'National Dialogue Quartet '}]},
  {'year': '2015',
   'category': 'physics',
   'laureates': [{'id': '919',
     'firstname': 'Takaaki',
     'surname': 'Kajita',
     'motivation': '"for the discovery of neutrino oscillations, which shows that neutrinos have mass"',
     'share': '2'},
    {'id': '920',
     'firstname': 'Arthur B.',
     'surname': 'McDonald',
     'motivation': '"for the discovery of neutrino oscillations, which shows that neutrinos have mass"',
     'share': '2'}]},
  {'year': '2015',
   'category': 'medicine',
   'laureates': [{'id': '916',
     'firstname': 'William C.',
     'surname': 'Campbell',
     'motivation': '"for their discoveries concerning a novel therapy against infections caused by roundworm parasites"',
     'share': '4'},
    {'id': '917',
     'firstname': 'Satoshi',
     'surname': 'Ōmura',
     'motivation': '"for their discoveries concerning a novel therapy against infections caused by roundworm parasites"',
     'share': '4'},
    {'id': '918',
     'firstname': 'Youyou',
     'surname': 'Tu',
     'motivation': '"for her discoveries concerning a novel therapy against Malaria"',
     'share': '2'}]},
  {'year': '2014',
   'category': 'chemistry',
   'laureates': [{'id': '909',
     'firstname': 'Eric',
     'surname': 'Betzig',
     'motivation': '"for the development of super-resolved fluorescence microscopy"',
     'share': '3'},
    {'id': '910',
     'firstname': 'Stefan W.',
     'surname': 'Hell',
     'motivation': '"for the development of super-resolved fluorescence microscopy"',
     'share': '3'},
    {'id': '911',
     'firstname': 'William E.',
     'surname': 'Moerner',
     'motivation': '"for the development of super-resolved fluorescence microscopy"',
     'share': '3'}]},
  {'year': '2014',
   'category': 'economics',
   'laureates': [{'id': '915',
     'firstname': 'Jean',
     'surname': 'Tirole',
     'motivation': '"for his analysis of market power and regulation"',
     'share': '1'}]},
  {'year': '2014',
   'category': 'literature',
   'laureates': [{'id': '912',
     'firstname': 'Patrick',
     'surname': 'Modiano',
     'motivation': '"for the art of memory with which he has evoked the most ungraspable human destinies and\r\nuncovered the life-world of the occupation"',
     'share': '1'}]},
  {'year': '2014',
   'category': 'peace',
   'laureates': [{'id': '913',
     'firstname': 'Kailash',
     'surname': 'Satyarthi',
     'motivation': '"for their struggle against the suppression of children and young people and for the right of all children to education"',
     'share': '2'},
    {'id': '914',
     'firstname': 'Malala',
     'surname': 'Yousafzai',
     'motivation': '"for their struggle against the suppression of children and young people and for the right of all children to education"',
     'share': '2'}]},
  {'year': '2014',
   'category': 'physics',
   'laureates': [{'id': '906',
     'firstname': 'Isamu',
     'surname': 'Akasaki',
     'motivation': '"for the invention of efficient blue light-emitting diodes which has enabled bright and energy-saving white light sources"',
     'share': '3'},
    {'id': '907',
     'firstname': 'Hiroshi',
     'surname': 'Amano',
     'motivation': '"for the invention of efficient blue light-emitting diodes which has enabled bright and energy-saving white light sources"',
     'share': '3'},
    {'id': '908',
     'firstname': 'Shuji',
     'surname': 'Nakamura',
     'motivation': '"for the invention of efficient blue light-emitting diodes which has enabled bright and energy-saving white light sources"',
     'share': '3'}]},
  {'year': '2014',
   'category': 'medicine',
   'laureates': [{'id': '903',
     'firstname': 'John',
     'surname': "O'Keefe",
     'motivation': '"for their discoveries of cells that constitute a positioning system in the brain"',
     'share': '2'},
    {'id': '904',
     'firstname': 'May-Britt',
     'surname': 'Moser',
     'motivation': '"for their discoveries of cells that constitute a positioning system in the brain"',
     'share': '4'},
    {'id': '905',
     'firstname': 'Edvard I.',
     'surname': 'Moser',
     'motivation': '"for their discoveries of cells that constitute a positioning system in the brain"',
     'share': '4'}]},
  {'year': '2013',
   'category': 'chemistry',
   'laureates': [{'id': '889',
     'firstname': 'Martin',
     'surname': 'Karplus',

In [32]:
prize2010 = pd.json_normalize(data = d['prizes'])

In [33]:
prize2010 #needs to be flattened/normalized

,year,category,laureates,overallMotivation
0,2020,chemistry,"[{'id': '991', 'firstname': 'Emmanuelle', 'sur...",NaN
1,2020,economics,"[{'id': '995', 'firstname': 'Paul', 'surname':...",NaN
2,2020,literature,"[{'id': '993', 'firstname': 'Louise', 'surname...",NaN
3,2020,peace,"[{'id': '994', 'motivation': '""for its efforts...",NaN
...,...,...,...,...
62,2010,literature,"[{'id': '854', 'firstname': 'Mario', 'surname'...",NaN
63,2010,peace,"[{'id': '855', 'firstname': 'Xiaobo', 'surname...",NaN
64,2010,physics,"[{'id': '849', 'firstname': 'Andre', 'surname'...",NaN
65,2010,medicine,"[{'id': '848', 'firstname': 'Robert G.', 'surn...",NaN

In [34]:
prize2010 = pd.json_normalize(data = d['prizes'], record_path = 'laureates', meta = ['year', 'category'])

In [35]:
prize2010

,id,firstname,surname,motivation,share,year,category
0,991,Emmanuelle,Charpentier,"""for the development of a method for genome ed...",2,2020,chemistry
1,992,Jennifer A.,Doudna,"""for the development of a method for genome ed...",2,2020,chemistry
2,995,Paul,Milgrom,"""for improvements to auction theory and invent...",2,2020,economics
3,996,Robert,Wilson,"""for improvements to auction theory and invent...",2,2020,economics
...,...,...,...,...,...,...,...
129,855,Xiaobo,Liu,"""for his long and non-violent struggle for fun...",1,2010,peace
130,849,Andre,Geim,"""for groundbreaking experiments regarding the ...",2,2010,physics
131,850,Konstantin,Novoselov,"""for groundbreaking experiments regarding the ...",2,2010,physics
132,848,Robert G.,Edwards,"""for the development of in vitro fertilization""",1,2010,medicine

In [2]:
#parsing web content html
url = 'https://www.formula1.com/en/results.html/2021/races/1067/monaco.html'

In [3]:
tables = pd.read_html(url)

In [4]:
tables #list of DF objects

[    Unnamed: 0 Pos  No                    Driver                        Car  \
 0          NaN   1  33      Max  Verstappen  VER      Red Bull Racing Honda
 1          NaN   2  55        Carlos  Sainz  SAI                    Ferrari
 2          NaN   3   4        Lando  Norris  NOR           McLaren Mercedes
 3          NaN   4  11        Sergio  Perez  PER      Red Bull Racing Honda
 4          NaN   5   5    Sebastian  Vettel  VET      Aston Martin Mercedes
 5          NaN   6  10        Pierre  Gasly  GAS           AlphaTauri Honda
 6          NaN   7  44      Lewis  Hamilton  HAM                   Mercedes
 7          NaN   8  18        Lance  Stroll  STR      Aston Martin Mercedes
 8          NaN   9  31        Esteban  Ocon  OCO             Alpine Renault
 9          NaN  10  99  Antonio  Giovinazzi  GIO  Alfa Romeo Racing Ferrari
 10         NaN  11   7      Kimi  Räikkönen  RAI  Alfa Romeo Racing Ferrari
 11         NaN  12   3    Daniel  Ricciardo  RIC           McLaren Mercedes
 12         NaN  13  14     Fernando  Alonso  ALO             Alpine Renault
 13         NaN  14  63      George  Russell  RUS          Williams Mercedes
 14         NaN  15   6     Nicholas  Latifi  LAT          Williams Mercedes
 15         NaN  16  22        Yuki  Tsunoda  TSU           AlphaTauri Honda
 16         NaN  17   9      Nikita  Mazepin  MAZ               Haas Ferrari
 17         NaN  18  47     Mick  Schumacher  MSC               Haas Ferrari
 18         NaN  NC  77     Valtteri  Bottas  BOT                   Mercedes
 19         NaN  NC  16     Charles  Leclerc  LEC                    Ferrari

     Laps Time/Retired  PTS  Unnamed: 8
 0     78  1:38:56.820   25         NaN
 1     78      +8.968s   18         NaN
 2     78     +19.427s   15         NaN
 3     78     +20.490s   12         NaN
 4     78     +52.591s   10         NaN
 5     78     +53.896s    8         NaN
 6     78     +68.231s    7         NaN
 7     77       +1 lap    4         NaN
 8     77       +1 lap    2         NaN
 9     77       +1 lap    1         NaN
 10    77       +1 lap    0         NaN
 11    77       +1 lap    0         NaN
 12    77       +1 lap    0         NaN
 13    77       +1 lap    0         NaN
 14    77       +1 lap    0         NaN
 15    77       +1 lap    0         NaN
 16    75      +3 laps    0         NaN
 17    75      +3 laps    0         NaN
 18    29          DNF    0         NaN
 19     0          DNS    0         NaN  ]

In [7]:
len(tables)

1

In [9]:
tables[0]

,Unnamed: 0,Pos,No,Driver,Car,Laps,Time/Retired,PTS,Unnamed: 8
0,NaN,1,33,Max Verstappen VER,Red Bull Racing Honda,78,1:38:56.820,25,NaN
1,NaN,2,55,Carlos Sainz SAI,Ferrari,78,+8.968s,18,NaN
2,NaN,3,4,Lando Norris NOR,McLaren Mercedes,78,+19.427s,15,NaN
3,NaN,4,11,Sergio Perez PER,Red Bull Racing Honda,78,+20.490s,12,NaN
4,NaN,5,5,Sebastian Vettel VET,Aston Martin Mercedes,78,+52.591s,10,NaN
5,NaN,6,10,Pierre Gasly GAS,AlphaTauri Honda,78,+53.896s,8,NaN
6,NaN,7,44,Lewis Hamilton HAM,Mercedes,78,+68.231s,7,NaN
7,NaN,8,18,Lance Stroll STR,Aston Martin Mercedes,77,+1 lap,4,NaN
8,NaN,9,31,Esteban Ocon OCO,Alpine Renault,77,+1 lap,2,NaN
9,NaN,10,99,Antonio Giovinazzi GIO,Alfa Romeo Racing Ferrari,77,+1 lap,1,NaN
10,NaN,11,7,Kimi Räikkönen RAI,Alfa Romeo Racing Ferrari,77,+1 lap,0,NaN
11,NaN,12,3,Daniel Ricciardo RIC,McLaren Mercedes,77,+1 lap,0,NaN
12,NaN,13,14,Fernando Alonso ALO,Alpine Renault,77,+1 lap,0,NaN
13,NaN,14,63,George Russell RUS,Williams Mercedes,77,+1 lap,0,NaN
14,NaN,15,6,Nicholas Latifi LAT,Williams Mercedes,77,+1 lap,0,NaN
15,NaN,16,22,Yuki Tsunoda TSU,AlphaTauri Honda,77,+1 lap,0,NaN
16,NaN,17,9,Nikita Mazepin MAZ,Haas Ferrari,75,+3 laps,0,NaN
17,NaN,18,47,Mick Schumacher MSC,Haas Ferrari,75,+3 laps,0,NaN
18,NaN,NC,77,Valtteri Bottas BOT,Mercedes,29,DNF,0,NaN
19,NaN,NC,16,Charles Leclerc LEC,Ferrari,0,DNS,0,NaN

In [11]:
Monaco21=tables[0]

In [13]:
Monaco21.columns

Index(['Unnamed: 0', 'Pos', 'No', 'Driver', 'Car', 'Laps', 'Time/Retired',
       'PTS', 'Unnamed: 8'],
      dtype='object')

In [18]:
Monaco21.drop(['Unnamed: 0', 'Unnamed: 8'], axis = 1)

,Pos,No,Driver,Car,Laps,Time/Retired,PTS
0,1,33,Max Verstappen VER,Red Bull Racing Honda,78,1:38:56.820,25
1,2,55,Carlos Sainz SAI,Ferrari,78,+8.968s,18
2,3,4,Lando Norris NOR,McLaren Mercedes,78,+19.427s,15
3,4,11,Sergio Perez PER,Red Bull Racing Honda,78,+20.490s,12
4,5,5,Sebastian Vettel VET,Aston Martin Mercedes,78,+52.591s,10
5,6,10,Pierre Gasly GAS,AlphaTauri Honda,78,+53.896s,8
6,7,44,Lewis Hamilton HAM,Mercedes,78,+68.231s,7
7,8,18,Lance Stroll STR,Aston Martin Mercedes,77,+1 lap,4
8,9,31,Esteban Ocon OCO,Alpine Renault,77,+1 lap,2
9,10,99,Antonio Giovinazzi GIO,Alfa Romeo Racing Ferrari,77,+1 lap,1
10,11,7,Kimi Räikkönen RAI,Alfa Romeo Racing Ferrari,77,+1 lap,0
11,12,3,Daniel Ricciardo RIC,McLaren Mercedes,77,+1 lap,0
12,13,14,Fernando Alonso ALO,Alpine Renault,77,+1 lap,0
13,14,63,George Russell RUS,Williams Mercedes,77,+1 lap,0
14,15,6,Nicholas Latifi LAT,Williams Mercedes,77,+1 lap,0
15,16,22,Yuki Tsunoda TSU,AlphaTauri Honda,77,+1 lap,0
16,17,9,Nikita Mazepin MAZ,Haas Ferrari,75,+3 laps,0
17,18,47,Mick Schumacher MSC,Haas Ferrari,75,+3 laps,0
18,NC,77,Valtteri Bottas BOT,Mercedes,29,DNF,0
19,NC,16,Charles Leclerc LEC,Ferrari,0,DNS,0

In [19]:
#Working with APIs

In [20]:
query = "https://data.kcmo.org/resource/dy5n-ewk5.json?$limit"

In [23]:
scooter_raw = pd.read_json(query)

In [24]:
scooter_raw.head()

,trip_id,startdate,starttime,enddate,endtime,tripduration,tripdistance,startlatitude,startlongitude,endlatitude,endlongitude,dayofweek,hour
0,a19320ed-7cd1-42da-bbd3-c14594e539c2,2019-12-21T00:00:00.000,17:45:00,2019-12-21T00:00:00.000,17:45:00,7,1.698,39.100,-94.587,39.097,-94.583,7,17
1,4317d776-0df3-4187-9fc2-767c59b05a97,2019-12-21T00:00:00.000,05:45:00,2019-12-21T00:00:00.000,05:45:00,9,4.335,39.109,-94.570,39.099,-94.550,7,5
2,27046b36-a5f2-4a31-b2ca-cc47f5912f3b,2019-12-21T00:00:00.000,22:00:00,2019-12-21T00:00:00.000,22:00:00,8,0.557,39.083,-94.582,39.090,-94.587,7,21
3,9ddf5ad6-8684-4f1b-8eb5-14d6d179f8a4,2019-12-21T00:00:00.000,20:00:00,2019-12-21T00:00:00.000,20:00:00,6,0.825,39.083,-94.582,39.085,-94.587,7,19
4,8516ca38-608e-4989-9670-be2dce55ac20,2019-12-21T00:00:00.000,16:30:00,2019-12-21T00:00:00.000,16:30:00,3,1.435,39.083,-94.582,39.089,-94.581,7,16

In [27]:
scooter_raw.columns #should have 15 rows with last to type 'point'

Index(['trip_id', 'startdate', 'starttime', 'enddate', 'endtime',
       'tripduration', 'tripdistance', 'startlatitude', 'startlongitude',
       'endlatitude', 'endlongitude', 'dayofweek', 'hour'],
      dtype='object')

In [26]:
scooter_raw.shape

(1000, 13)